[phases.setup]
nixPkgs = ["python39", "nodejs", "ffmpeg"]  # Incluye Node.js y ffmpeg (necesario para Python)

[phases.install]
cmds = [
    "pip install -r requirements.txt",  # Instala dependencias de Python
    "npm ci"                            # Instala dependencias de Node.js
]
dependsOn = ["setup"]

[phases.start]
cmd = "bash start.sh"                   # Usa un script para iniciar ambas apps
